# ===========================================
# Information Settings
# ===========================================

#navigation
menu:
  article: /
  archives: /archives
  tags: /tags
  about: /about
  rss: /atom.xml
  travelling: https://www.travellings.cn/plain.html

# favicon
favicon: /favicon.ico

# ===========================================
# Color&Schemes Setting
# ===========================================

## Common

# Navigator Language
local-nav: true

# Mobile-Header
# light | dark
mobile-header: light

# Scheme
# banderole | balance
scheme: banderole

# Header Style
# line | block
header-style: block

# theme-style
# default: dark | green | blue | purple
# miku | sakura | snowmiku
theme-style: sakura

# ===========================================
# Article Setting
# ===========================================

# Navigator in post
toc: true

# Use copyright infomation
copyright:
  enable: true
  license: 'License: <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0 License</a>'

#Reword button or message(fill your QRCode of any Pay.)
reward:
  enable: false
  # message:
  qrcode:
    # alipay:
    #   url:
    #   message:
    # wechat:
    #   url:
    #   message:
    # paypal:
    #   url:
    #   message:

# ===========================================
# Social Contact
# ===========================================

# Comments // Please only switch one on.
comments:
  enable: true

  utterances: true

  # disqus:
  # livere_datauid:

  # changyan:
  #   appid:
  #   appkey:

  # gitalk:
  #   owner:
  #   repo:
  #   client_id:
  #   client_secret:
  #   admin:

# sub //Please just fill out ID.
sub:
  # facebook:
  # twitter:
  # instagram:
  # weibo:
  # zhihu:
  github: 84634E1A607A
  # linkedin:
  # douban:
  # medium:
  # yuque:

#Friend link
# friendLink:

# ===========================================
# Analytics
# ===========================================

# analytics:
#   google:
#   baidu:

#visit_count(Powered by busuanzi on http://busuanzi.ibruce.info/)
visit_count: false

# ===========================================
# Theme Settings
# ===========================================

# pjax
pjax: true

# mathjax
mathjax: false
mathjax3: true

# lightbox
lightbox: true

# lazyload
lazyload: true

# animate (Powered by Syuanpi on https://colmugx.github.io/Syuanpi.css)
animate: true

# Created Time
since: 2024

# plugin
# plugins:

# about
# self:

# ===========================================
# Search Settings
# ===========================================

# Search
search:
  enable: true
  label: Search something?

# ===========================================
# Documents Styles
# ===========================================

# article-fonts
# default | Simsun | YaHei | Hel | Custom
fonts-style: default

# code-fonts
# default | Custom
code-style: default

# ===========================================
# WebApp Settings (iOS)
# ===========================================


# ===========================================
# Version
# ===========================================
version: 3.0

#theme_author: Co1MugX
